### PR TITLE
Change OCI image to new ROCK

### PR DESCRIPTION
**Pull request by jardon**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature

* **What is the current behavior?** (You can also link to an open issue here)
The charm pulls the upstream image from `mongo`.

* **What is the new behavior (if this is a feature change)?**
The charm pulls the new ROCK from `dataplatformoci`

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No.

* **Other information**:
[MongoDB ROCK Docker Hub](https://hub.docker.com/r/dataplatformoci/mongodb)

### CODE REVIEW

**Comment by jardon** [comment]
This PR can be merged once this [PR](https://github.com/canonical/mongodb-rock/pull/6) for updating `mongodb-rock` is merged.

**Review by MiaAltieri — COMMENTED** [review]
looks good once mongosh is installed

**Review by taurus-forever — APPROVED** [review]
Is it ready for the review? The code is LGTM, but tests polishing might still be necessary.

**Review by MiaAltieri — APPROVED** [review]
awesome work

**Pull request merged**
