### PR TITLE
[DPE-5289]: CI runs on new juju versions

### PR DESCRIPTION
**Pull request by Gu1nness**
* Use juju 3.5.3 in regular runs
 * Runs also 3.6/beta on nightly runs

### CODE REVIEW

**Review by carlcsaposs-canonical — DISMISSED** [review]
you may need to specify base when deploying with libjuju so that it doesn't default to focal cc @shayancanonical

**Comment by Gu1nness** [comment]
> you may need to specify base when deploying with libjuju so that it doesn't default to focal cc @shayancanonical

In the end I was asked to remove the nightly runs on 3.6 so it shouldn't be an issue anymore, right?

**Review by Mehdi-Bendriss — DISMISSED** [review]

**Comment by carlcsaposs-canonical** [comment]
> so it shouldn't be an issue anymore, right

think so!

**Review by MiaAltieri — COMMENTED** [review]
Does test_mongos.py fail due to this bump? Or does it fail generally?

**Comment by Gu1nness** [comment]
> Does test_mongos.py fail due to this bump? Or does it fail generally?

It fails generally, it is missing a retry for the `get_related_username_password`. We had the same issue on MongoDB VM a few weeks ago with `get_connection_string` if you remember.
It will be fixed when the `secret-data` ticket will be fixed.

**Review by MiaAltieri — APPROVED** [review]

**Review by Mehdi-Bendriss — APPROVED** [review]

**Pull request merged**
