### PR TITLE
Fixes for building charm

### PR DESCRIPTION
**Pull request by dmitry-ratushnyy**
To fix issues with build we need to pin version of pluggy to 1.2.0

### CODE REVIEW

**Comment by juditnovak** [comment]
Guys, I'm really not sure what I'm talking about... :sweat_smile: 

But after discussions with @carlcsaposs-canonical on this particular thing, I understood that we have a solution available without any additional pinning on charms side.

We just need to use v5 for the corresponding github action.
```
canonical/data-platform-workflows/.github/workflows/build_charms_with_cache.yaml@v5
```
(Proof is on https://github.com/canonical/mongodb-k8s-operator/pull/200)

**Comment by juditnovak** [comment]
BTW that seems to be what other charms are doing as well:

https://github.com/canonical/mysql-k8s-operator/blob/main/.github/workflows/ci.yaml#L37

**Review by delgod — DISMISSED** [review]

**Review by delgod — DISMISSED** [review]

**Review by MiaAltieri — DISMISSED** [review]

**Comment by dmitry-ratushnyy** [comment]
@juditnovak, looks like  canonical/data-platform-workflows/.github/workflows/build_charms_with_cache.yaml@v5 is not working on CI and causing [ issue crashes ](https://github.com/canonical/mongodb-k8s-operator/actions/runs/6273354876)

**Comment by juditnovak** [comment]
WOW, I'm very glad that the githb action was useful at the end :-)

**Review by delgod — APPROVED** [review]

**Review by MiaAltieri — APPROVED** [review]

**Pull request merged**
