### PR TITLE
[DPE-3383] fix dashboard 6/edge

### PR DESCRIPTION
**Pull request by MiaAltieri**
## Issue
1. Dashboard wasn't showing metrics

## Solution
Update dashboard to show metrics
 
Screenshot 2024-01-30 at 15 05 59

### CODE REVIEW

**Review by Mehdi-Bendriss — APPROVED** [review]

**Review by dmitry-ratushnyy — APPROVED** [review]

**Comment by petrutlucian94** [comment]
@Mehdi-Bendriss I think I'm hitting this issue, is there any chance you could publish a new revision on Charmhub? The last edge revision (40) was published on 14 Dec 2023 and doesn't include this fix.

**Comment by petrutlucian94** [comment]
I've tried building the charm manually but it fails to install:

```
mongodb-k8s/2   error     idle   10.1.8.139         hook failed: "install"
```

```
unit-mongodb-k8s-0: 11:20:02 WARNING unit.mongodb-k8s/0.install Traceback (most recent call last):
unit-mongodb-k8s-0: 11:20:02 WARNING unit.mongodb-k8s/0.install   File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/./src/charm.py", line 13, in <module>
unit-mongodb-k8s-0: 11:20:02 WARNING unit.mongodb-k8s/0.install     from charms.mongodb.v0.helpers import (
unit-mongodb-k8s-0: 11:20:02 WARNING unit.mongodb-k8s/0.install   File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/lib/charms/mongodb/v0/helpers.py", line 13, in <module>
unit-mongodb-k8s-0: 11:20:02 WARNING unit.mongodb-k8s/0.install     from charms.mongodb.v0.mongodb import MongoDBConfiguration, MongoDBConnection
unit-mongodb-k8s-0: 11:20:02 WARNING unit.mongodb-k8s/0.install   File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/lib/charms/mongodb/v0/mongodb.py", line 12, in <module>
unit-mongodb-k8s-0: 11:20:02 WARNING unit.mongodb-k8s/0.install     from bson.json_util import dumps
unit-mongodb-k8s-0: 11:20:02 WARNING unit.mongodb-k8s/0.install ModuleNotFoundError: No module named 'bson'
```

**Comment by Mehdi-Bendriss** [comment]
Hi @petrutlucian94 - we released a new edge version a few weeks ago (revision 41) - could you check if the issue persists?

**Comment by petrutlucian94** [comment]
@Mehdi-Bendriss It works, thanks!

**Pull request merged**
